#ifndef CONSTS_H
#define CONSTS_H

#define PLANT_LOCATION_LAT 48.956
#define PLANT_LOCATION_LNG 11.629

#define AZIMUTH_ENABLED
#define ELEVATION_ENABLED

// sensors
#define AZIMUTH_SCALE 0.47125815
#define AZIMUTH_OFFSET -32

#define ELEVATION_SCALE 0.06481311055
#define ELEVATION_OFFSET 4.85

// limits
#define AZIMUTH_MIN 50
#define AZIMUTH_MAX 300
#define AZIMUTH_TOLERANCE 2

#define ELEVATION_MIN 15
#define ELEVATION_MAX 65
#define ELEVATION_TOLERANCE 1

// storm position
#define STORM_AZIMUTH 180
#define STORM_ELEVATION ELEVATION_MAX

#define TIMEZONE_OFFSET 1

// pin configuration
#define PIN_AZIMUTH_SENSOR A2
#define PIN_ELEVATION_SENSOR A1
#define PIN_STORM_SWITCH A7
#define PIN_ELEVATION_UP 3
#define PIN_ELEVATION_DOWN 4
#define PIN_AZIMUTH_RIGHT 6
#define PIN_AZIMUTH_LEFT 5

#define SOFTWAREI2C_ENABLE 1
#define SOFTWAREI2C_SDA  A3
#define SOFTWAREI2C_SCL  A4


// 
#define DIRECTION_LEFT 1
#define DIRECTION_RIGHT 2
#define DIRECTION_UP 1
#define DIRECTION_DOWN 2

#define MODE_MANUAL 1
#define MODE_NORMAL 2
#define MODE_NIGHT 3
#define MODE_MORNING 4
#define MODE_STORM 5

#endif